trigger:
  branches:
    include:
      - main
      - experiment-release
      - release

pool:
  vmImage: 'windows-2019'

# User defined parameters
variables:
  - group: CO_DevOpsAutomation

jobs:
  - job: Sync_main_toGSK
    displayName: 'synchronizing EY main to GSK main'
    steps:
    - task: PowerShell@2
      displayName: 'PowerShell Script'
      inputs:
        targetType: filePath
        filePath: 'AzurePipelines/BranchAutomation/SyncRepoTask.ps1'
        arguments: "
        -userName           $(Build.QueuedBy)
        -ori_token          $(System.AccessToken)
        -ori_Repo_link      $(System.CollectionUri)$(System.TeamProject)/_git/$(Build.Repository.Name)
        -ori_Repo_name      $(Build.Repository.Name)
        -ori_branch         'main'
        -tar_token          $(GskGitHub_HRTP_PAT)
        -tar_Repo_link      $(GskGitHub_baseurl)/$(GskGitHub_HRTP_Backend_repo)
        -tar_branch         'main'
        "

  - job: Sync_release_toGSK
    displayName: 'synchronizing EY release to GSK release'
    steps:
    - task: PowerShell@2
      displayName: 'PowerShell Script'
      inputs:
        targetType: filePath
        filePath: 'AzurePipelines/BranchAutomation/SyncRepoTask.ps1'
        arguments: "
        -userName           $(Build.QueuedBy)
        -ori_token          $(System.AccessToken)
        -ori_Repo_link      $(System.CollectionUri)$(System.TeamProject)/_git/$(Build.Repository.Name)
        -ori_Repo_name      $(Build.Repository.Name)
        -ori_branch         'release'
        -tar_token          $(GskGitHub_HRTP_PAT)
        -tar_Repo_link      $(GskGitHub_baseurl)/$(GskGitHub_HRTP_Backend_repo)
        -tar_branch         'release'
        "

  - job: Sync_experiment_release_toGSK
    displayName: 'synchronizing EY experiment-release to GSK experiment-release'
    steps:
    - task: PowerShell@2
      displayName: 'PowerShell Script'
      inputs:
        targetType: filePath
        filePath: 'AzurePipelines/BranchAutomation/SyncRepoTask.ps1'
        arguments: "
        -userName           $(Build.QueuedBy)
        -ori_token          $(System.AccessToken)
        -ori_Repo_link      $(System.CollectionUri)$(System.TeamProject)/_git/$(Build.Repository.Name)
        -ori_Repo_name      $(Build.Repository.Name)
        -ori_branch         'experiment-release'
        -tar_token          $(GskGitHub_HRTP_PAT)
        -tar_Repo_link      $(GskGitHub_baseurl)/$(GskGitHub_HRTP_Backend_repo)
        -tar_branch         'experiment-release'
        "